### ISSUE TITLE
project without cocoapod

### ISSUE THREAD

**Issue by Rufy86** [gali8/WhichFont#1]
is it possible to have a version without cocoapod?

**Comment by gali8** [comment]
Sure but not yet. I'm in vacation without my mac.
What's wrong with cocoapods??

Daniele Galiotto | www.nexor.it

Inviato da iPhone

**Comment by Rufy86** [comment]
I haven't cocoapods and I'm sorry I hate it. I prefer to install manually all frameworks. in addition to this, on raywenderlich site there is a tutorial that use the framework of tesseract. and I think is better.

**Comment by gali8** [comment]
You can follow the wiki page of tesseracr ocr ios on github.
Is exactly explained how to manually install the framework and how to use it.

Daniele Galiotto | www.nexor.it

Inviato da iPhone

**Comment by gali8** [comment]
Just follow the other thread https://github.com/gali8/WhichFont/issues/2 :)
